options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: "us-central1-docker.pkg.dev/${PROJECT_ID}/docker/docker-reuse"

steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE}", "."]

images:
  - ${_IMAGE}
